# Site settings
title: Adimwit's Blog
email: huynhduykevin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog to explore the many facets of computer science, mathematics, and life, all driven by the imagination called curiosity.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adimwit.github.io" # the base hostname & protocol for your site
github_username:  Adimwit

# Build settings
markdown: kramdown

#highlighter: pygments